Module2 task1
htmlacademy-php/2009683-yeticave-12 pull request #4
Opened 2022-03-11 19:03 UTC by artcio

Добавил каталог товаров и несколько товаров. Задание 2.5. Проработка массивов и циклов.

2022-03-12 12:12 UTC, tagedo requested changes
Вася, по работе с массивами все хорошо. Исправь, пожалуйста, то, что касается расположения массивов в файле и наименований.

2022-03-12 12:12 UTC, tagedo commented on index.php
> +              ];
Объявление массивов лучше переместить в самое начало скрипта, выше начала верстки.
Название переменных - важно. Они должны быть информативными. Например, массив категорий лучше назвать $categories, а массив товаров - $products. 
При переборе массива текущий элемент лучше называть не $val и $val1, а $category и $product.

2022-03-12 12:12 UTC, tagedo commented on index.php
> +             ];
я бы не сокращала $category до $cat - ключи должны быть максимально понятны по своему смыслу

2022-03-17 17:26 UTC, main-tenance approved these changes
Все хорошо!

2022-03-17 17:27 UTC, merged